# Generated by Django 4.2.1 on 2023-05-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_alter_my_user_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_User',
        ),
    ]
