# Generated by Django 4.1.7 on 2023-05-20 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0003_delete_my_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='superior_Employee',
            new_name='created_By',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role_Created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role_Modified',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_Modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 5, 54, 41, 106951, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='role',
            name='role_Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 5, 54, 41, 106455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='role',
            name='role_Modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 5, 54, 41, 106650, tzinfo=datetime.timezone.utc)),
        ),
    ]
