# Generated by Django 4.2.1 on 2023-05-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zip_code', models.IntegerField()),
                ('zone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Adress Models',
            },
        ),
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_Name', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
            ],
            options={
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('role_Created', models.DateTimeField(auto_now_add=True)),
                ('role_Modified', models.DateTimeField(auto_now=True)),
                ('superior_Employee', models.CharField(max_length=100)),
                ('reporting_Person', models.CharField(max_length=200)),
                ('registration_Date', models.DateField(auto_now_add=True)),
                ('Adress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userData.adress')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userData.role')),
            ],
        ),
    ]
